# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pesquisa.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaPesquisa(object):
    def setupUi(self, TelaPesquisa):
        TelaPesquisa.setObjectName("TelaPesquisa")
        TelaPesquisa.resize(1008, 600)
        self.centralwidget = QtWidgets.QWidget(TelaPesquisa)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_editarpesquisa = QtWidgets.QPushButton(self.frame)
        self.btn_editarpesquisa.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_editarpesquisa.setFont(font)
        self.btn_editarpesquisa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_editarpesquisa.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_editarpesquisa.setObjectName("btn_editarpesquisa")
        self.gridLayout_4.addWidget(self.btn_editarpesquisa, 0, 0, 1, 1)
        self.btn_excluirpesquisa = QtWidgets.QPushButton(self.frame)
        self.btn_excluirpesquisa.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_excluirpesquisa.setFont(font)
        self.btn_excluirpesquisa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluirpesquisa.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_excluirpesquisa.setObjectName("btn_excluirpesquisa")
        self.gridLayout_4.addWidget(self.btn_excluirpesquisa, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 2, 1, 1)
        self.btn_homepesquisa = QtWidgets.QPushButton(self.frame)
        self.btn_homepesquisa.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_homepesquisa.setFont(font)
        self.btn_homepesquisa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_homepesquisa.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.btn_homepesquisa.setObjectName("btn_homepesquisa")
        self.gridLayout_4.addWidget(self.btn_homepesquisa, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.list_pesquisa = QtWidgets.QListView(self.frame_2)
        self.list_pesquisa.setObjectName("list_pesquisa")
        self.gridLayout_3.addWidget(self.list_pesquisa, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_pesquisa = QtWidgets.QLineEdit(self.frame_3)
        self.txt_pesquisa.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_pesquisa.setObjectName("txt_pesquisa")
        self.horizontalLayout.addWidget(self.txt_pesquisa)
        self.btn_pesquisa = QtWidgets.QPushButton(self.frame_3)
        self.btn_pesquisa.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_pesquisa.setFont(font)
        self.btn_pesquisa.setObjectName("btn_pesquisa")
        self.horizontalLayout.addWidget(self.btn_pesquisa)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        TelaPesquisa.setCentralWidget(self.centralwidget)

        self.retranslateUi(TelaPesquisa)
        QtCore.QMetaObject.connectSlotsByName(TelaPesquisa)

    def retranslateUi(self, TelaPesquisa):
        _translate = QtCore.QCoreApplication.translate
        TelaPesquisa.setWindowTitle(_translate("TelaPesquisa", "MainWindow"))
        self.btn_editarpesquisa.setText(_translate("TelaPesquisa", "EDITAR"))
        self.btn_excluirpesquisa.setText(_translate("TelaPesquisa", "EXCLUIR"))
        self.btn_homepesquisa.setText(_translate("TelaPesquisa", "HOME"))
        self.btn_pesquisa.setText(_translate("TelaPesquisa", "Pesquisar"))
